from setuptools import setup, find_packages
from functools import reduce

long_description = """The AI Fairness 360 toolkit is an open-source library to help detect and mitigate bias in machine
learning models. The AI Fairness 360 Python package includes a comprehensive set of metrics for datasets and models to
test for biases, explanations for these metrics, and algorithms to mitigate bias in datasets and models.

We have developed the package with extensibility in mind. This library is still in development. We encourage the
contribution of your datasets, metrics, explainers, and debiasing algorithms."""

version = '0.1.0'

# with open("aif360/version.py", 'w') as f:
#     f.write('# generated by setup.py\nversion = "{}"\n'.format(version))

extras = {
#     'OptimPreproc': ['cvxpy>=1.0'],
#     'LFR': ['numba>=0.42.0'],
#     'AdversarialDebiasing': ['tensorflow>=1.13.1,<2'],
#     'DisparateImpactRemover': ['BlackBoxAuditing'],
#     'LIME': ['lime'],
#     'ART': ['adversarial-robustness-toolbox>=1.0.0'],
    'notebooks': ['jupyter', 'tqdm']
}
# extras['tests'] = reduce(lambda l1, l2: l1+l2, extras.values(), ['pytest>=3.5'])
# extras['docs'] = ['sphinx', 'sphinx_rtd_theme']
# extras['all'] = list(reduce(lambda s, l: s.union(l), extras.values(), set()))

setup(name='nero',
      version=version,
      description='NERO semi-supervised learning',
      author='NERO developers',
#       author_email='',
      url='https://github.com/bhomass/NERO.git',
      long_description=long_description,
      long_description_content_type='text/markdown',
      license='MIT License',
      packages=[pkg for pkg in find_packages()],
      python_requires='>=3.5',
      install_requires=[
          'numpy>=1.19.5',
          'scipy>=1.5.3',
          'pandas>=0.24.0',
          'tqdm',
          'requests',
          'ujson'
      ],
      extras_require=extras,
      package_data={'NERO': ['data/*', 'data/*/*']},
      include_package_data=True,
      zip_safe=False)
